on:
  workflow_dispatch:

jobs:
  build:
    name: Generate build tools for Windows Server 2022
    runs-on: windows-2022
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      - name: run build tools
        shell: cmd
        run: |
          cmd /c "%GITHUB_WORKSPACE%\main.bat"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ms_buildtools.zip
